version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day-of-month: "1"
    open-pull-requests-limit: 0
    groups:
      github_actions_all:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types:
          [
            "version-update:semver-major",
            "version-update:semver-minor",
            "version-update:semver-patch",
          ]
